# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: Install Python
          working_directory: 
          command:  |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - run: docker build -t flystr .
      - run: docker save -o flystr_image flystr
      - run: scp -o StrictHostKeyChecking=no flystr_image root@139.59.132.144:~/flystr_image
      - run: ssh -o StrictHostKeyChecking=no  root@139.59.132.144 -- docker load -i flystr_image
      - run: ssh -o StrictHostKeyChecking=no  root@139.59.132.144 -- docker-compose up -d

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master